# Generated by Django 2.2.11 on 2020-03-25 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferencemodel',
            name='path',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
