# Generated by Django 2.2.11 on 2020-03-27 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0003_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 27, 19, 7, 47, 919405)),
        ),
    ]
