# Generated by Django 2.2.11 on 2020-03-28 09:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0004_file_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 3, 28, 9, 59, 27, 630668, tzinfo=utc)),
        ),
    ]
