# Generated by Django 2.2.11 on 2020-03-28 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0006_auto_20200328_1146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='date',
        ),
    ]
