# Generated by Django 2.2.11 on 2020-03-28 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0008_file_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
