# Generated by Django 2.2.11 on 2020-03-28 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0009_auto_20200328_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
    ]
