# Generated by Django 2.2.11 on 2020-03-29 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0012_file_calculation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='File',
        ),
        migrations.AlterField(
            model_name='inferenceinstance',
            name='calculation_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inference_app.InferenceModel'),
        ),
        migrations.AlterField(
            model_name='inferenceinstance',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inference_app.Camera'),
        ),
        migrations.AlterField(
            model_name='inferenceinstance',
            name='value',
            field=models.CharField(default='', max_length=10000),
        ),
    ]
