# Generated by Django 2.2.11 on 2020-03-29 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0013_auto_20200329_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
