# Generated by Django 2.2.11 on 2020-03-30 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0014_auto_20200329_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferenceinstance',
            name='camera',
        ),
        migrations.DeleteModel(
            name='Camera',
        ),
    ]
