# Generated by Django 2.2.11 on 2020-03-30 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0015_auto_20200330_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inferenceinstance',
            name='calculation_model',
        ),
        migrations.DeleteModel(
            name='InferenceModel',
        ),
    ]
