# Generated by Django 2.2.11 on 2020-03-30 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0016_auto_20200330_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='InferenceModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.FileField(blank=True, upload_to='post_image')),
                ('version', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='inferenceinstance',
            name='calculation_model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inference_app.InferenceModel'),
        ),
    ]
