# Generated by Django 2.2.11 on 2020-03-30 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0018_camera'),
    ]

    operations = [
        migrations.AddField(
            model_name='inferenceinstance',
            name='camera',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='inference_app.Camera'),
        ),
    ]
