# Generated by Django 2.2.11 on 2020-03-30 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inference_app', '0019_inferenceinstance_camera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inferenceinstance',
            name='value',
            field=models.CharField(max_length=10000),
        ),
    ]
